### ISSUE TITLE
Transformations

### ISSUE THREAD

**Issue by refactorthis** [serilog/serilog-sinks-elasticsearch#43]
Hi,

This is more of a question than an issue and I'm new to ELK so may be somewhat nieve.  I've inherited a codebase that uses serilog to log large arbitrary objects when writing log statements. Usually these represent the state the method is in (local variables, etc). Each log is different and the names of variables are not standardized across all statements. Sometimes large complex object graphs are logged.

1. I guess the first question is,  is serilog meant to be used in this way? I see the benefit of having the field structured in the index when that field is standardized and can be aggregated or queried, but not so much when I just want the values logged to the 'message' field. (Which is analyzed in es anyways)
2. Is there an issue with having a few thousand fields in an es index. And should I be changing these log messages so that they don write arbitrarily deep structures?
3. Should I manually create the index and allow serilog to push whatever documents it likes but only index on the fields I am interested in standardizing and querying outside of the message field. 

Thanks very much

**Comment by nblumhardt** [comment]
Hi Brent,

I can't answer the ELK questions, but regarding the first part of 1), no, that's not really the _design_ intention for Serilog.

It can be done, but the goal for Serilog's object graph serialization is to improve the machine readability of log events with interesting data **that you'd otherwise normally format into unstructured text**, not to capture large/complex object graphs.

As a rule of thumb - if you'd bother converting the data to some string format for inclusion in a traditional text log, then Serilog should handle recording that same data in structured form.

So, say, if the code records a user login and we want to log the username as well as the internal id of the user, then logging a structured `User` property with `Name` and `Id` seems fine to me. Likewise if we're starting up and want to log the list of configuration servers we're about to probe, then `Servers` structured as s list of hostnames is great. In these cases I'd historically have written the same data out to the log just by formatting it into the message, and Serilog makes the event more useful by preserving the structure.

As a counterexample, I haven't worked with many systems where it's been desirable log e.g. entire messages from a service bus, or entire web requests from clients, except in perhaps the most extreme, all-else-has-failed debugging scenario. Pumping these kinds of things out into a text log would be pretty commonly recognised as a questionable practice I think. Serilog's not much different here - the purpose of the log and the natural limitations WRT event size and so-on remain, even though the format is more modern.

Hope I've understood your question correctly and not just hit you with a wall of text :-O ... hope this helps! :-)

Nick

**Comment by refactorthis** [comment]
Thanks very much Nick, you validated what I was thinking. Looks like I'll have to start simplifying some of these log statements.
