### ISSUE TITLE
Configure the sink missing defaults

### ISSUE THREAD

**Issue by etiennedetrace** [serilog/serilog-sinks-elasticsearch#56]
Would have been nice to have all the default values in the Wiki. Had to pull source to find a waste of a few minutes. BufferLogShippingInterval is 5 seconds but I suspected that it may be far less. Good to know what the standard is before tweaking. 

https://github.com/serilog/serilog-sinks-elasticsearch/wiki/Configure-the-sink

**Comment by chuwik** [comment]
Hi @etiennedetrace, I have updated the wiki with the defaults (adjusted some old values and updated those that were missing). Thanks for pointing this out, and sorry you lost a bit of time looking for that value!

@mivano, you may want to have a look at the wiki page to see if I missed something?

**Comment by mivano** [comment]
Thanks @chuwik 

I quickly looked through it and noticed the minimum log event level. It think this is informational, instead of verbose: https://github.com/serilog/serilog-sinks-elasticsearch/blob/defba05c1d61d81347f86af6f6a508d8a200edf5/src/Serilog.Sinks.Elasticsearch/LoggerConfigurationElasticSearchExtensions.cs#L60

ConnectionTimeout is a nice one; in the comments in the class it says 5 sec, in the code 60 secs :-)

**Comment by chuwik** [comment]
I checked LevelAlias.Minimum in the main serilog repo and it's set to Verbose; I believe that's what's being picked up by the es sink? Or is it overriden somewhere?

**Comment by mivano** [comment]
Ah yes, you are right. Thanks for updating the wiki page and I will close this ticket. @etiennedetrace let us know if you think more is needed.
